### ISSUE TITLE
LTE training on 360 images

### ISSUE THREAD

**Issue by caozidong** [jaewon-lee-b/ltew#1]
Hello, thanks very much for your intelligent work about image super-resolution (LTE) and image warping (LTEW), which gives me much guidance.

My problem is that: when I use LTE or LIIF for training the 360 image super-resolution task, using datasets provided by LAU-Net [1], the ws-psnr metric degrades during training, and the performance is bad. However, when using EDSR with pixel-shuffle for up-sampling, the training process has no problem.

I wonder if you have encountered similar problems, and if you have some possible solutions to address training on 360 images (ERP images).

[1] LAU-Net: Latitude Adaptive Upscaling Network for Omnidirectional Image Super-Resolution

**Comment by jaewon-lee-b** [comment]
Hi @caozidong

We found that LTE or LTEW even converges with 360 datasets when we use rectangular patches (e.g., 128x16) instead of square patches (e.g., 48x48) as training inputs.

We hypothesize that deep neural networks should see vertical information simultaneously since 360 images show severe distortion near boundaries.

p.s. Images in 360 datasets have severe JPEG distortion to meet the hardware-limited constraints. Therefore network should be capable of removing artifacts.

**Comment by caozidong** [comment]
Thanks for your patience!
